### ISSUE TITLE
Xamarin support tracking issue

### ISSUE THREAD

**Issue by davidfowl** [aspnet/SignalR#1886]
There's a bunch of work that is planned but that is also required to make SignalR work. There is an issue in System.Memory preventing it from being used in Xamarin applications. This issue is tracking the work that is being done in corefx to remedy the situation.

**Comment by anurse** [comment]
We also need to determine our plan for MsgPack in Xamarin. If we support it in the initial release, we need to make sure it's configured appropriately to not use Reflection.Emit.

**Comment by elusiven** [comment]
Is there an actual version that actually works? Trying to get this to work but getting system.memory error all the time.

**Comment by digitalkirkley** [comment]
I found to get Android building, directly reference: system.memory
Then to get running, copy over to debug/Android/assets at post build time: 
system.io.pipelines, system.threading.tasks.extensions, system.buffers, system.runtime.compilerservices.unsafe

**Comment by FrancoisM** [comment]
Version="1.0.0-preview2-final" doesn't build for iOS project on VS 2017 15.6.6

Failed to resolve "System.Buffers.IBufferWriter`1" reference from "System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"

**Comment by mikaelm12** [comment]
@muratg I'd need access to a build with these fixes

**Comment by muratg** [comment]
@mikaelm12 sounds good, punting the verification out of the milestone.

**Comment by davidfowl** [comment]
@akoeplinger any more details you can give here?

**Comment by FrancoisM** [comment]
With latest VS for mac 15.7 preview, the AOT compilation error goes away.
https://stackoverflow.com/questions/49646078/xamrin-ios-aot-compilation-fails-from-mac-but-builds-fine-from-pc/49699385#49699385

However, on iOS, the following error remains even with rc1-final.

Failed to resolve "System.Buffers.IBufferWriter`1" reference from "System.Memory, Version=4.0.1.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"

**Comment by akoeplinger** [comment]
We added the System.Memory.dll facade (that's why the AOT error went away) but we haven't added all the types yet. I'll find out where we're tracking that :)

**Comment by FrancoisM** [comment]
It's an issue on both iOS and Android actually.

**Comment by FrancoisM** [comment]
The AOT error didn't go away because I upgraded signalr (it was on preview 1), it went away because I upgraded vs 4 mac :-)

**Comment by FrancoisM** [comment]
BTW, I'm lost.
System.Memory 4.0.1.0 is in .Net Core 2.1. So how can it be used by Xamarin anyway?

**Comment by FrancoisM** [comment]
Also, if I change the linker behavior to "Don't link" then I get another error:

Could not AOT the assembly '/Users/francois/Library/Caches/Xamarin/mtbs/builds/AotTests.iOS/678ab06afbe35836bdafdf91a7d48f1c/obj/iPhone/Debug/mtouch-cache/Build/System.IO.Pipelines.dll'

This is strange because I thought the aot errors where caused by the new way of referencing packages and that it was solved with VS 15.7 (and indeed the previous aot error I raised was solved), as explained [here](https://stackoverflow.com/questions/49646078/xamrin-ios-aot-compilation-fails-from-mac-but-builds-fine-from-pc).

**Comment by AwsomeCode** [comment]
System.Memory 4.0.1.0 is not support on mono framework 5.10 which is in 15.7.
Ref https://releases.xamarin.com/release-15-7/

Support mono version will be 5.12 or above. which are not release yet.
Ref https://github.com/xamarin/xamarin-android/pull/1509

**Comment by FrancoisM** [comment]
But why do you use version 4.0.1.0 which is in net core and not in mono when maybe you could use 4.5.0 which (I think) is net standard and already referenced as a nuget package?

**Comment by FrancoisM** [comment]
Morover, if somewhere you use version 4.0.1.0, why isnt there a `#if NETCOREAPP2_1`  to prevent it from being compiled in the net standard version consummed by xamarin?

**Comment by AArayeshi** [comment]
I have sane issue. It works with windows version but not with Android and IOS.

**Comment by FrancoisM** [comment]
@AwsomeCode, you said that `System.Memory` is not supported on Mono framework and will be on 5.12 or above. How can we know if a library is supported by mono? Is there a list somewehere (maybe [that ](https://github.com/mono/mono/blob/mono-5.12.0.226/mono/metadata/assembly.c))? I upgraded VS for mac to the version 7.6 preview which has Mono 5.12.0.226 but the error remains.

**Comment by davidfowl** [comment]
@michelmoorlag Can you clarify what you mean? You need to use ASP.NET Core SignalR to use **Microsoft.AspNetCore.SignalR.Client** on the client.

**Comment by michelmoorlag** [comment]
@davidfowl My current signalR server is written with 'classic' asp.net technology and I am using the Microsoft.AspNet.SignalR.Client from my XF app to access it. Now I have rewritten my signalR server with asp.net core technology. I tried to access the new .net core signalR server with the 'classis' Microsoft.AspNet.SignalR.Client but then you get a 404 not found error. After googeling I found that the .net core signalR technology is incompatible with the 'classic' signalR technology and I needed to use the new Microsoft.AspNetCore.SignalR.Client which I tried but ended me up on this page. So that is what i mean with 

> The old client is not compatible with the new server (and vice versa)

**Comment by mvanhalen** [comment]
The issue still exists in Visual Studio 15.8.0 Preview 1.1. Is there any workaround?

**Comment by anurse** [comment]
There is no workaround at this time. We are working directly with the Xamarin team to get more information and will update this thread when we have the information.

**Comment by michelmoorlag** [comment]
Issue [mono#8623](https://github.com/mono/mono/issues/8623) has been done and closed but the milestone part is empty. Does this mean we wil have a solution soon? My migration process has been stopped in it's tracks because of this and I'm awaiting a solution.

**Comment by anurse** [comment]
There is a fix going in to dotnet/corefx to resolve the issue temporarily: https://github.com/dotnet/corefx/issues/29847

This won't be making the RTM release, but we anticipate getting it in place for the first patch release.

**Comment by mintyfusion** [comment]
Is there a timeline when a first patch is going out?

**Comment by anurse** [comment]
There is no public timeline, but we are aiming to get the patch out fairly soon after RTM (which is imminent).

**Comment by marchanddesable** [comment]
I'm also blocked with the issue Failed to resolve "System.Buffers.IBufferWriter`1" reference on IOS
This is a BIG problem, I was already late... ):

**Comment by marchanddesable** [comment]
So, IOS doesn't work, and same for Android: System.IO.FileNotFoundException: Could not load assembly 'System.Memory, Version=4.0.1.0 ...

My work is blocked ):

**Comment by AwsomeCode** [comment]
Are u using uwp as well?

**Comment by marchanddesable** [comment]
No only IOS and Android + .Net core 2.x

**Comment by anurse** [comment]
@marchanddesable It's not possible to work around this which is why this is one of our highest priorities for the first patch release. We don't have it fully locked down, but we're getting it out as quickly as possible. We weren't able to get official Xamarin support on the schedule for 2.1.0, but it's a high priority now that the RTM is out the door.

**Comment by eopeter** [comment]
Any news on the Xamarin Support resolution. Will be very much appreciated for a pending deliverable.

**Comment by digitalkirkley** [comment]
@anurse Will we see the patch release for Xamarin support be made available before the end of this month?

**Comment by anurse** [comment]
We are working towards a patch release this month, but there are a number of moving parts so I can't guarantee anything right now. This is a very high priority for us, so we're working to get it resolved as quickly as possible.

**Comment by alexsorokoletov** [comment]
Just checked latest MyGet builds (Microsoft.AspNetCore.SignalR.Client Version 1.0.1-rtm-30843 and System.Memory Version 4.6.0-preview3-26501-04) and the issue is still there. Maybe this will save time for other people desperately looking for any alternatives.

Glad to see this is a high priority, on the other hand wondering how we all ended up with no workarounds at all. 

Will be checking if we can use this on iOS https://github.com/DyKnow/SignalR-ObjC and this  on Android https://github.com/SignalR/java-client meanwhile 

Or something from these old samples (includes source code and .dll binaries for both platforms)
https://github.com/shanselman/PanTiltZoomSystem/tree/master/PTZRemoteController-iOS
https://github.com/shanselman/PanTiltZoomSystem/tree/master/PTZRemoteController-Android

**Comment by marchanddesable** [comment]
As @alexsorokoletov said,  "wondering how we all ended up with no workarounds at all"
I use SignalR since the very first version (I was even using Comet with long polling before that), this is the first time I see an isssue like this with no alternative.

I totaly understand that you guys have a lot of work to do to make it work again.
But for some of us, the situation is very scary, because even when the issues will be fixed, we will still wonder if It is a good idea to continue working with Signalr.

I use signalr in the project I'm about to start, on Web, IOS and Android. 
This is a Startup project, with fund raising in a few month. 
One of the main features is a WebRTC video conferencing app with SignalR for the signaling steps of the communication, before the peer2peer connection.

Because of the situation I have to work on other parts of the project and expect the issue to be fixed soon. The more I wait, the more the situation becomes complicated because I will run out of funds.

If I was already in production, I would not be able to sleep with an issue like that : )

So maybe the team should provide us some alternatives in case something like that happen again in the future.

**Comment by FrancoisM** [comment]
Maybe you should raise funds to write an alternative to signalr then?😂😂😂😂😂😂

**Comment by marchanddesable** [comment]
Hahaha there is no reason to do that, SignalR is exactly what we need.
There are other options like WebSync, but they don't have a .net core version and it's not free.
Really, the problem here is not the issues, it's more the situation "no other options" :)

I love the crazy work that you do on SignalR, I have seen this library growing years after years, since the first version and this is why I made the choice to use it.

**Comment by mterwoord** [comment]
Maybe step up and see if you can work around things yourself (or fix
things)? Isn't that the power of open source?


2018-06-07 8:46 GMT+02:00 marchanddesable <notifications@github.com>:

**Comment by FrancoisM** [comment]
Sure but here's how you sound to me:" I raised funds trying to get rich using a free library and I'm not happy that it doesn't work".

**Comment by davidfowl** [comment]
We're actively working on the issue, we can't go any faster. We fixed the what thought was the main issue and another one popped up. We're not looking for ways to fix that one. Stay tuned...

**Comment by marchanddesable** [comment]
@davidfowl Thank you for the informations!

@FrancoisM Trust, me, I'm not that kind of person : )
Raising fund is still a goal to reach "later", I'm not here yet.
I have worked for more than 2 years on this project "for free", with only expenses, 0 earnings, no guarantees that it will work as expected.
And the potential fund raising is to try to build a team, not to become rich... : )

**Comment by FrancoisM** [comment]
Fair enough ;-)

**Comment by davidfowl** [comment]
The passion is great! 😄 I love SignalR too 😉

**Comment by cwrea** [comment]
Anybody interested in this issue might also want to track the issue I opened for Xamarin.iOS specifically w.r.t. System.Memory: [iOS app build fails when referencing package (e.g. Entity Framework Core 2.1) that depends on newer System.Memory](https://github.com/xamarin/xamarin-macios/issues/4168).

**Comment by alexsorokoletov** [comment]
Here is a poor man's workaround I found so far.

I’ve used SignalR libaries from here https://github.com/shanselman/PanTiltZoomSystem/lib with one little change. These dlls use non-signed Newtonsoft.Json so in runtime whole thing just does not work. I’ve “ildasm+ilasm” them to specify public token in the Newtonsoft.Json:
![image](https://user-images.githubusercontent.com/1788581/41131314-229c86a0-6a89-11e8-8ca0-d9e938899372.png)
After that change, I was able to use the updated library in Xamarin.iOS both in debug and release, even with a newer version of Newtonsoft.Json (I already had it referenced in the project). I can send and receive messages. Server side runs latest SignalR server SDK (Hail to the compatibility!)
The same trick workes with Android as well.

The updated iOS and Android libraries can be downloaded here:
https://github.com/DreamTeamMobile/PanTiltZoomSystem/blob/master/lib/Microsoft.AspNet.SignalR.Client.iOS.dll

https://github.com/DreamTeamMobile/PanTiltZoomSystem/blob/master/lib/Microsoft.AspNet.SignalR.Client.Android.dll

**Comment by davidfowl** [comment]
@alexsorokoletov isn't that ASP.NET SignalR? That's not compatible with ASP.NET Core SignalR. Am I missing something?

**Comment by FrancoisM** [comment]
For those who *really* want a workaround, just make an hybrid view and delegate the interaction with your backend to the js client library.

**Comment by alexsorokoletov** [comment]
@davidfowl, please forgive me for my lame question. What is the right way to get Xamarin SignalR SDK that works with classic ASP.NET? 
Which package/version?

**Comment by anurse** [comment]
The [`Microsoft.AspNet.SignalR.Client`](https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Client) package is the client for ASP.NET SignalR. It supports .NET Standard, so it should work on Xamarin. If you have any issues with it, you should report those on the http://github.com/SignalR/SignalR repository

**Comment by alexsorokoletov** [comment]
Indeed, I got somehow confused by the package that we use on the server - `Microsoft.AspNet.SignalR` and one of it's dependencies `Microsoft.AspNet.SignalR.Core` https://www.nuget.org/packages/Microsoft.AspNet.SignalR.Core/. Thank you for clarification and sorry for the noise, should've RTFM first.

**Comment by pravinpatil83** [comment]
We are also waiting for the release with Xamarin support. But those who are looking for a workaround, Microsoft.AspNetCore.SignalR.Client 1.0.0-preview1-final is working fine in Xamarin.

**Comment by marianogenovese** [comment]
this exception is related to this issue?:
```
System.TypeLoadException: Could not resolve the signature of a virtual method
  at System.Reflection.MonoCMethod.InternalInvoke (System.Object obj, System.Object[] parameters) [0x0001b] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Reflection.MonoCMethod.DoInvoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0007a] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Reflection.MonoCMethod.Invoke (System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at System.Reflection.ConstructorInfo.Invoke (System.Object[] parameters) [0x00000] in <f32579baafc1404fa37ba3ec1abdc0bd>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x00035] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00056] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0002d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0000d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00072] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor (Microsoft.Extensions.DependencyInjection.ServiceLookup.ConstructorCallSite constructorCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0001b] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00056] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped (Microsoft.Extensions.DependencyInjection.ServiceLookup.ScopedCallSite scopedCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0002d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitSingleton (Microsoft.Extensions.DependencyInjection.ServiceLookup.SingletonCallSite singletonCallSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0000d] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[TArgument,TResult].VisitCallSite (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, TArgument argument) [0x00072] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve (Microsoft.Extensions.DependencyInjection.ServiceLookup.IServiceCallSite callSite, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x00000] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine+<>c__DisplayClass1_0.<RealizeService>b__0 (Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope scope) [0x0003e] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType, Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope serviceProviderEngineScope) [0x00032] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService (System.Type serviceType) [0x00008] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService (System.Type serviceType) [0x00000] in <15b87bbf30da4bf4b95652066811831b>:0 
  at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T] (System.IServiceProvider provider) [0x0000e] in <0483c335f48f46709723603c1a3a0703>:0 
  at Microsoft.AspNetCore.SignalR.Client.HubConnectionBuilder.Build () [0x00041] in <b0d1d37b5fba4e70bb8beedfba950c0d>:0 
  at SignalRAndroid.MainActivity.OnCreate (Android.OS.Bundle savedInstanceState) [0x00023] in C:\Users\mariano\src\signalr\SignalRAndroid\SignalRAndroid\MainActivity.cs:29 
```

**Comment by eopeter** [comment]
@pravinpatil83 the Microsoft.AspNetCore.SignalR.Client 1.0.0-preview1-final compiles on the iOS Simulator but I get a System.Buffer exception on the physical device. Are you able to get it to run on the device with the preview?

**Comment by marianogenovese** [comment]
@pravinpatil83 I could not compile it on a 5.1 android using Microsoft.AspNetCore.SignalR.Client 1.0.0-preview1-final

**Comment by marianogenovese** [comment]
VS15.8 preview (https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes) include a fix for this issue?

**Comment by anurse** [comment]
The current released preview **does not** contain a fix. I believe the fix is targeting the next preview.

**Comment by pravinpatil83** [comment]
@eopeter @marianogenovese I am using preview package in my development project and it's working for some time. I have created a new [GitHub repository](https://github.com/pravinpatil83/signalr_xamarin_preview_package_demo) to demonstrate. it worked on my machine. I have not tested it elsewhere. The new project structure is different and it doesn't contain the packages.config file but I added a list of packages in a readme.

**Comment by marianogenovese** [comment]
@pravinpatil83 thank i saw what you did, and I was able to create a connection from android using 1.0.0-preview1-final.

**Comment by shkaan** [comment]
For me preview1 client works on android v7 nougat physical device and on emulators v5 - v7, also it works on iOS emulators but does not compile on iOS 11 physical device.

**Comment by mintyfusion** [comment]
Preview1 works for both iOS and Android, but Android we can't enable "Linking" for Release mode. In debug linking works for some reason though.

**Comment by anurse** [comment]
I have confirmation that the fix is expected to arrive in 15.8 and should be available in the next preview release (Preview 3). I have confirmed that SignalR is working on Android with the fix, but I'm still working on confirming iOS.

I wouldn't recommend downgrading to preview 1 for any kind of production workload since there were a number of critical issues fixed after preview 1

**Comment by anurse** [comment]
I've now confirmed both Android and iOS scenarios work in the upcoming Xamarin build. To make it absolutely clear, to resolve this issue you will need to:

1. Upgrade `Microsoft.AspNetCore.SignalR.Client` to `1.0.1`. This build is **not yet available** on NuGet, but we expect to be releasing it next week.
2. Upgrade Xamarin to the appropriate version:
    * Xamarin.Android `8.4.0.1`
    * Xamarin.iOS `11.14.0.4`
    * These will be included in:
      * Visual Studio 15.8 **Preview 3** (not yet released)
      * Visual Studio for Mac 7.6 **Preview 3** (also not yet released; will be available in the Alpha and Beta channels in VS for Mac)

I'm going to close this issue as we now believe all known Xamarin issues are resolved. If you are still encountering issues **after** updating to those versions, please file a new issue! Make sure to note the Xamarin versions you are using in the issue so we can accurately reproduce your environment.

**Comment by anurse** [comment]
The packages are now available on NuGet. At this time, the Visual Studio (Windows and Mac) updates are still not yet public.

Please note that additional dependencies may be required (two packages that SignalR references transitively need to be upgraded). See https://github.com/aspnet/Announcements/issues/305 for more detail.

**Comment by eopeter** [comment]
I am able to build with just the 2.1.1 signalR client update without any update to Visual Studio. Have not tested sending messages but the project builds

**Comment by anurse** [comment]
I believe that is expected. The `1.0.1` patch fixes build-time issues but there are still some runtime issues that require the Xamarin fix. But hey, if it works for you, great! :)

**Comment by titonton** [comment]
@anurse there is a build-time issue when trying to build for a physical iPhone device. Something with the System.Memory. I'll let you know what the full error is. The only person with the iPhone just left the office

**Comment by titonton** [comment]
@anurse I saw the disclaimer you had written in the Xamarin folder in the samples and I wanted to let you know that at least for me it's not working with the most recent stable packages. I had written a new issue here https://github.com/aspnet/SignalR/issues/2518 . Apologies if it's a repeat of another issue. I just thought that it might be something different this time.

**Comment by GMariakis** [comment]
So while we wait for VS to get updated, how do we go about updating Xamarin manually as per item 3: [https://github.com/aspnet/Announcements/issues/305](url)

**Comment by anurse** [comment]
I don't believe the Xamarin versions are available other than through Visual Studio previews.

**Comment by kevinvella** [comment]
@anurse I updated to SignalR version 1.0.1 and it worked on iphone simulator debug mode ( I can't check on a real device as i don't have any)

On Android it gave me this error:
Unable to connect to the server with any of the available transports.


Setting SignalR on server
```
app.UseSignalR((HubRouteBuilder obj) => 
            {
                obj.MapHub<MessagingHub>("/messanger",(Microsoft.AspNetCore.Http.Connections.HttpConnectionDispatcherOptions obj) => 
                {
                    obj.Transports = Microsoft.AspNetCore.Http.Connections.HttpTransportType.WebSockets;
                });

            });
```

Here is the details of visual studio:
=== Visual Studio Community 2017 for Mac ===

Version 7.5.3 (build 7)
Installation UUID: 867dfddd-5059-4764-be12-3125347a8abf
Runtime:
	Mono 5.10.1.57 (2017-12/ea8a24b1bbf) (64-bit)
	GTK+ 2.24.23 (Raleigh theme)
	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)

	Package version: 510010057

=== NuGet ===

Version: 4.3.1.4445

=== .NET Core ===

Runtime: /usr/local/share/dotnet/dotnet
Runtime Versions:
	2.0.6
	2.0.5
	2.0.3
	2.0.0
	1.1.6
	1.0.9
SDK: /usr/local/share/dotnet/sdk/2.1.101/Sdks
SDK Versions:
	2.1.101
	2.1.4
	2.0.3
	2.0.0
	1.1.7
MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.10.1/lib/mono/msbuild/15.0/bin/Sdks

=== Xamarin.Profiler ===

Version: 1.6.2
Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler

=== Apple Developer Tools ===

Xcode 9.4.1 (14161)
Build 9F2000

=== Xamarin.Mac ===

Version: 4.4.1.193 (Visual Studio Community)

=== Xamarin.iOS ===

Version: 11.12.0.4 (Visual Studio Community)
Hash: 64fece5f
Branch: d15-7
Build date: 2018-05-29 20:00:44-0400

=== Xamarin.Android ===

Version: 8.3.3.2 (Visual Studio Community)
Android SDK: /Users/kevin/Library/Developer/Xamarin/android-sdk-macosx
	Supported Android versions:
		2.3    (API level 10)
		4.3    (API level 18)
		4.4    (API level 19)
		4.4.87 (API level 20)
		5.0    (API level 21)
		5.1    (API level 22)
		6.0    (API level 23)
		7.0    (API level 24)
		7.1    (API level 25)
		8.0    (API level 26)
		8.1    (API level 27)

SDK Tools Version: 26.1.1
SDK Platform Tools Version: 28.0.0
SDK Build Tools Version: 28.0.0 rc1

Java SDK: /usr
java version "1.8.0_162"
Java(TM) SE Runtime Environment (build 1.8.0_162-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.162-b12, mixed mode)

Android Designer EPL code available here:
https://github.com/xamarin/AndroidDesigner.EPL

=== Xamarin Inspector ===

Version: 1.4.0
Hash: b3f92f9
Branch: master
Build date: Fri, 19 Jan 2018 22:00:34 GMT
Client compatibility: 1

=== Build Information ===

Release ID: 705030007
Git revision: 13cecd02aceddf29a1ed57b86f81c02994df1483
Build date: 2018-06-14 15:48:08-04
Xamarin addins: 7065de97cf22c9038fdc39dd627f2c30790fd8af
Build lane: monodevelop-lion-d15-7

=== Operating System ===

Mac OS X 10.13.5
Darwin 17.6.0 Darwin Kernel Version 17.6.0
    Tue May  8 15:22:16 PDT 2018
    root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64

=== Enabled user installed addins ===

LiveXAML 1.3.31
Prism Template Pack 2.0.0
Gorilla Player 1.2.0.6
Internet of Things (IoT) development (Preview) 7.5

**Comment by freever** [comment]
Hey guys, just wanted to let you know that all is working for me again with VS Mac Version 7.6 Preview (7.6 build 1773) (Android and iOS) and VS Windows 15.7.4 (Android)

**Comment by shkaan** [comment]
Android and UWP projects build ok, but for iOS i'M getting this error:

`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(791,3): error : Failed to resolve "System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder" reference from "System.Threading.Tasks.Extensions, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51"`

All my projects are referencing SignalR 1.0.1,  System.Threading.Tasks.Extensions version 4.5.1 and System.Runtime.CompilerServices.Unsafe version 4.5.1.

Visual Studio Professional 15.7.4
Xamarin iOS 11.12.0.4

**Comment by mintyfusion** [comment]
Is anyone see linking issues in Release Mode for Android? The debug version compiles fine.

Error		The "LinkAssemblies" task failed unexpectedly.
Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA2006: Could not resolve reference to 'System.Threading.ValueAwaiter`1' (defined in assembly 'Microsoft.AspNetCore.Sockets.Client.Http, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60') with scope 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. When the scope is different from the defining assembly, it usually means that the type is forwarded. ---> Mono.Cecil.ResolutionException: Failed to resolve System.Threading.ValueAwaiter`1

Visual Studio Professional 15.7.4
Xamarin.Android SDK   8.3.3.2 (HEAD/dffc59120)

**Comment by meijeran** [comment]
As said by @anurse  before, there is also a xamarin update required to get everything to work, Probably the upcoming xamarin updates will fix your problem.

**Comment by anurse** [comment]
> I really hope so, but @anurse also said that SignalR 1.0.1 should fix build time problems

To clarify, it solves IL build-time issues, however iOS requires ahead-of-time native compilation and it will fail there.

**Comment by shkaan** [comment]
Got it, will wait for Xamarin update.

**Comment by reznor244** [comment]
I've updated to Visual Studio 2017 15.8 Preview 3 which includes Xamarin.Android 8.4.0.1 and Xamarin.iOS 11.14.0.4, installed Microsoft.AspNetCore.SignalR.Client and Microsoft.AspNetCore.SignalR.Client.Core 1.0.1 and am still getting this error when trying to build my Android app on Xamarin Forms.

**Comment by eopeter** [comment]
After updating to all the latest bits as suggested to fix the issue by @anurse , I was still having issue and the fix for me was to create a new project and copy files over. (was a pain but works after that)

**Comment by eopeter** [comment]
Maybe delete all packages from project and reopen the project may be a quicker way to get all fresh libraries but didn't try it

**Comment by anurse** [comment]
@reznor244 did you also install the additional dependencies listed in https://github.com/aspnet/Announcements/issues/305 ?

@eopeter Hrm, I wouldn't have thought you'd have to recreate the project. I didn't have to do that, but I had a very simple test project. Glad it did work out in the end...

**Comment by anurse** [comment]
Can you provide you `obj/project.assets.json` file and the `PackageReference` nodes in your `csproj`? Please post them to a [gist](https://gist.github.com/) or something similar and link them as the files are quite large. Also note that these will include all Package IDs and Versions you are referencing so if there's any sensitive information in that, you should filter it out before posting it.

**Comment by reznor244** [comment]
These are from a fresh test project I created to try to see if I could get it to build, so no sensitiveinfo.

TestSignalRClient.csproj: https://gist.github.com/reznor244/2f5bcac412060400c5b0119d75925f9a
TestSignalRClient.Android.csproj: https://gist.github.com/reznor244/e80bc2339dcb37f67f32a69e1c61ed9d
project.assets.json (from TestSignalRClient): https://gist.github.com/reznor244/798a3f1fc89dd98d2d5d51fb376fcee3

**Comment by anurse** [comment]
Hrm, I'm not able to reproduce this with our [Xamarin.Forms client](https://github.com/aspnet/SignalR-samples/tree/anurse/xamarin/Xamarin).

Can you push your test project up to a GitHub repo and open a **new** issue for this? I want to try reproducing this with exactly the same project you are. Please also include your Xamarin versions so I can compare them with the ones I'm using.

**Comment by MagicAndre1981** [comment]
With [1.0.2](https://www.nuget.org/packages/Microsoft.AspNetCore.SignalR.Client/1.0.2) I get [System.IO.FileNotFoundException: Could not load file or assembly 'System.Numerics.Vectors, Version=4.1.3.0](https://github.com/xamarin/xamarin-android/issues/2037) on Android with Xamarin. The UWP Xamarin project works fine.

**Comment by MagicAndre1981** [comment]
ok, I just saw the[ announcement](https://github.com/aspnet/Announcements/issues/305) and need to wait for 15.8 update to get it working.

**Comment by marchanddesable** [comment]
15.8.0 Preview 4.0 is released

**Comment by MagicAndre1981** [comment]
@marchanddesable there is already[ Preview 5](https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-preview-relnotes#--visual-studio-2017-version-158-preview-5-), but I don't want to install a Preview, I want a stable version.

**Comment by MagicAndre1981** [comment]
ok, the 15.8 Preview 5 works. So I wasted some time to figure this out. 

@anurse 

The [docs are wrong](https://docs.microsoft.com/en-us/aspnet/core/signalr/dotnet-client?view=aspnetcore-2.1) until 15.8 gets out:

> The ASP.NET Core SignalR .NET client can be used by **Xamarin**

Because of this statement I did not expect my issue.

**Comment by titonton** [comment]
Any update on this since 15.8.1 is out now? I don't want to update just yet because last time I did, Xamarin.iOS wasn't working at the time and I had to uninstall VS, resulting in losing my keystore.

**Comment by MagicAndre1981** [comment]
@titonton 15.8.1 works for Android if I use packages.config. I can't speak about iOS.

**Comment by reznor244** [comment]
I was able to use it with iOS on a shared project. I was unable to get it to work on .NET Standard 2.0 because mtouch would fail to link Systems.Threading.Tasks.Extensions 4.5.1 because of some reference issues ([see xamarin-macos issue #4629](https://github.com/xamarin/xamarin-macios/issues/4629)). There may be a work around, but I stripped out the feature requiring SignalR (business decision to put the new feature on hold). Hopefully that is resolved in next update.

**Comment by KSemenenko** [comment]
Remove the app.config from the project. It helped me for Xamarin.iOS and Xamarin.Andoird

**Comment by BillyMutt** [comment]
Based on the info here aspnet/Announcements#305 I was hoping to finally get my Xamarin iOS client working with ASP.Net Core SignalR, but still no luck. I get an exception when the client tries to connect to the hub:

    //  Connect to the SignalR hub.
    string url = $"http://{DataService.HostName}:{DataService.MainPort.ToString()}/hub";
    try
    {
        MediaHubConnection = new HubConnectionBuilder().WithUrl(url).Build();
    }
    catch (Exception e)
    { // Handle exception }

> Exception: A suitable constructor for type Microsoft.AspNetCore.SignalR.Client.HttpConnectionFactory could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

The code above works in the iPhone simulator, but crashes on the device itself.

I am using Visual Studio 15.8.0 with Xamarin iOS 11.14.0.13 on Windows 10; Visual Studio for Mac 7.6.1 Build 9 with Xamarin iOS 11.14.0.13 on the Mac. Latest released Nugets for AspNetCore SignalR (server and client).

Any help is highly appreciated.

**Comment by BillyMutt** [comment]
Just to close the loop: more info [here](https://github.com/aspnet/SignalR/issues/2933). Much thanks to @anurse for helping out.

**Comment by rs1t** [comment]
@anurse Hey! Is there any way to use SignalR Client 1.0.0-preview1-final in Xamarin? Exactly this version is used on server and I can't affect this. 

If I set linker behavior to `Don't link` then I'll get runtime exception:
 `Could not load type of field 'Microsoft.AspNetCore.Sockets.Client.ServerSentEventsTransport:_memoryPool' (0) due to: Could not resolve type with token 01000064 (from typeref, class/assembly System.Buffers.MemoryPool, System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60) assembly:System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 type:System.Buffers.MemoryPool member:(null) signature:<none>` after calling hubConnection.StartAsync(). There are no compile errors, though.

But if I use `Link All` I will get build time error: 
`Error MT2101: Can't resolve the reference 'System.Void System.Buffers.MemoryPool::.ctor()', referenced from the method 'System.Void Microsoft.AspNetCore.Sockets.Client.ServerSentEventsTransport::.cctor()' in 'System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60'. (MT2101) (Coinlion.iOS)`
or with `Link framework SDKs only`:
`error MT2002: Failed to resolve "System.IO.Pipelines.PipeReader" reference from "System.IO.Pipelines, Version=0.1.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60"`

There is part of my `Link framework SDKs only` build log with additional `-v -v -v -v` mtouch arguments (unrelated info removed): 
https://gist.github.com/rs1t/4cb71af7750bb9c34a40a63105f5c776
And packages.config:
https://gist.github.com/rs1t/1fe3be9ee801a2d4858c400db43d8131

I have latest VS Mac and Xamarin versions (the issue was present with earlier versions as well):

> === Visual Studio Community 2017 for Mac ===
> 
> Version 7.6.7 (build 49)
> Installation UUID: 82d8c3be-5d15-42ff-b578-d2b5bb3b8c97
> Runtime:
> 	Mono 5.12.0.301 (2018-02/4fe3280bba1) (64-bit)
> 	GTK+ 2.24.23 (Raleigh theme)
> 	Xamarin.Mac 4.4.1.178 (master / eeaeb7e6)
> 
> 	Package version: 512000301
> 
> === NuGet ===
> 
> Version: 4.3.1.4445
> 
> === .NET Core ===
> 
> Runtime: /usr/local/share/dotnet/dotnet
> Runtime Version: 2.1.2
> SDK: /usr/local/share/dotnet/sdk/2.1.302/Sdks
> SDK Version: 2.1.302
> MSBuild SDKs: /Library/Frameworks/Mono.framework/Versions/5.12.0/lib/mono/msbuild/15.0/bin/Sdks
> 
> === Xamarin.Profiler ===
> 
> Version: 1.6.3
> Location: /Applications/Xamarin Profiler.app/Contents/MacOS/Xamarin Profiler
> 
> === Apple Developer Tools ===
> 
> Xcode 10.0 (14320.25)
> Build 10A255
> 
> === Xamarin.Mac ===
> 
> Version: 4.6.0.14 (Visual Studio Community)
> Hash: 1a6e2786
> Branch: 
> Build date: 2018-08-28 00:12:06-0400
> 
> === Xamarin.iOS ===
> 
> Version: 12.0.0.15 (Visual Studio Community)
> Hash: 84552a46
> Branch: xcode10
> Build date: 2018-09-17 21:54:33-0400
> 
> === Xamarin.Android ===
> 
> Version: 9.0.0.20 (Visual Studio Community)
> Android SDK: /Users/ddrobotov/Library/Developer/Xamarin/android-sdk-macosx
> 	Supported Android versions:
> 		4.2 (API level 17)
> 		4.4 (API level 19)
> 		7.1 (API level 25)
> 		8.1 (API level 27)
> 
> SDK Tools Version: 26.1.1
> SDK Platform Tools Version: 28.0.1
> SDK Build Tools Version: 27.0.3
> 
> Java SDK: /usr
> java version "1.8.0_181"
> Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
> Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
> 
> Android Designer EPL code available here:
> https://github.com/xamarin/AndroidDesigner.EPL
> 
> === Xamarin Inspector ===
> 
> Version: 1.4.3
> Hash: db27525
> Branch: 1.4-release
> Build date: Mon, 09 Jul 2018 21:20:18 GMT
> Client compatibility: 1
> 
> === Build Information ===
> 
> Release ID: 706070049
> Git revision: 0b48ccfb376397678b3bc3653da2c6603d35357d
> Build date: 2018-09-20 21:14:23+00
> Build branch: release-7.6
> Xamarin extensions: b25fd1e2b9a7859aff9536924e8edb6cbfb78637
> 
> === Operating System ===
> 
> Mac OS X 10.13.6
> Darwin 17.7.0 Darwin Kernel Version 17.7.0
>     Fri Jul  6 19:54:51 PDT 2018
>     root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64

**Comment by MagicAndre1981** [comment]
@rs1t 
why not update the server and client to last stable version?

**Comment by rs1t** [comment]
My backend dev say that there are problems with errors handling in new SignalR, for example instead of "user not found" we get "generic error" which causes problems with tests. And this app is not the only client, so updating may take a while.

**Comment by anurse** [comment]
Nope, the preview builds had critical issues that prevented them from working with Xamarin. We fixed this in the final client release.

> My backend dev says that there are problems with error handling in new SignalR, for example instead of "user not found" we get "generic error" which causes problems with tests.

Please file these issues and we can look at resolving them.
